language: shell

env:
  global:
    - CIBW_SKIP="cp27*"
    - CIBW_BEFORE_BUILD="pip install cython numpy"
    - TWINE_USERNAME=__token__
    # TWINE_PASSWORD should be set to an API token in the Travis settings
  jobs:
    - CONDA_PYTHON=3.5
    - CONDA_PYTHON=3.6
    - CONDA_PYTHON=3.7
    - CONDA_PYTHON=3.8

os:
  - linux
  - windows
  - osx

stages:
  - test
  - name: deploy
    if: tag IS PRESENT AND repo = sintefmath/Splipy

before_install:
  - source ./ci/before_install.sh

install:
  - source ./ci/install.sh
  - conda install -y python=${CONDA_PYTHON}
  - pip install -r requirements.txt
  - pip install twine cibuildwheel==1.1.0
  - |-
    if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then
        pip install opencv-python
    fi
  - conda list

script:
  - python setup.py install
  - pytest test --benchmark-skip

jobs:
  include:
    - stage: deploy
      name: Deploy source distribution
      script: python setup.py sdist --formats=gztar
      after_success: python -m twine upload --skip-existing dist/*.tar.gz
    - stage: deploy
      name: Build and deploy Linux wheels
      services: docker
      script: python -m cibuildwheel --output-dir wheelhouse
      after_success: python -m twine upload --skip-existing wheelhouse/*.whl
    - stage: deploy
      name: Build and deploy OSX wheels
      os: osx
      script: python -m cibuildwheel --output-dir wheelhouse
      after_success: python -m twine upload --skip-existing wheelhouse/*.whl
    - stage: deploy
      name: Build and deploy Windows wheels
      os: windows
      script: python -m cibuildwheel --output-dir wheelhouse
      after_success: python -m twine upload --skip-existing wheelhouse/*.whl

notifications:
  email:
    on_success: never
    on_failure: always
