# language: python
# sudo: false
# python:
#   - "3.5"
#   - "3.6"
# install:
#   - pip install -r requirements.txt
#   - python setup.py build_ext
#   - python setup.py install
# script:
#   - which pytest
#   - python -c "import splipy; print(splipy.__path__)"
#   - pytest .

language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env:
        - PIP=pip
        - CIBW_SKIP="cp27-* cp33-*"
    - os: osx
      language: generic
      env:
        - PIP=pip2
        - CIBW_SKIP="cp27-* cp33-*"

script:
  - $PIP install cibuildwheel==0.7.1
  - cibuildwheel --output-dir wheelhouse
