FIND_LIBRARY(OpenNURBS_LIBRARIES
  NAMES openNURBS
)

FIND_PATH(OpenNURBS_INCLUDE_DIRS
  NAMES opennurbs.h
  PATH_SUFFIXES libopennurbs
)

INCLUDE(FindPackageHandleStandardArgs)
IF(OpenNURBS_LIBRARIES AND OpenNURBS_INCLUDE_DIRS)
  FIND_PACKAGE_HANDLE_STANDARD_ARGS(OpenNURBS DEFAULT_MSG
                                    OpenNURBS_LIBRARIES
                                    OpenNURBS_INCLUDE_DIRS)
ENDIF(OpenNURBS_LIBRARIES AND OpenNURBS_INCLUDE_DIRS)

MARK_AS_ADVANCED(OpenNURBS_LIBRARIES OpenNURBS_INCLUDE_DIRS)
